version: "3"
services:
  opa:
    image: openpolicyagent/opa
    ports:
    - 8181:8181
    command:
    - "run"
    - "--server"
    - "--log-level=debug"
    - "--server-diagnostics-buffer-size=1000"
#    - "--config-file=/config/opa-config.txt"
    - "/data"
    volumes:
    - ./opa-config/opa-server/config:/config
    - ./opa-config/policies/data/system/diagnostics:/data

  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
    - ./opa-config/prometheus/:/etc/prometheus/
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
    - 9090:9090

  grafana:
    image: grafana/grafana
    depends_on:
    - prometheus
    ports:
    - 3000:3000
    volumes:
    - ./opa-config/grafana/provisioning/:/etc/grafana/provisioning/