global:
  scrape_interval: 5s

scrape_configs:
- job_name: "opa"
  metrics_path: "/metrics"
  static_configs:
  - targets:
    - "localhost:8181"
- job_name: "userservice"
  metrics_path: "/actuator/prometheus"
  static_configs:
  - targets:
    - "localhost:8080"