apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-bad-labels
  labels:
    type: bad
    context: bad
spec:
  replicas: 1
  selector:
    matchLabels:
      type: bad
      context: bad
  template:
    metadata:
      labels:
        type: bad
        context: bad
    spec:
      containers:
      - name: nginx
        image: nginx:1.10
